//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.AdminMasterCategory {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminMasterCategory.IMasterCategory")]
    public interface IMasterCategory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryUpdate", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryUpdateResponse")]
        void Admin_MasterCategoryUpdate(int categoryId, string categoryName, string viewTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryUpdate", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryUpdateResponse")]
        System.Threading.Tasks.Task Admin_MasterCategoryUpdateAsync(int categoryId, string categoryName, string viewTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryGet", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryGetResponse")]
        System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryGet", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryGetResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO>> Admin_MasterCategoryGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryCheckExistsResponse")]
        System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryCheckExists(string categoryName, int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryCheckExistsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO>> Admin_MasterCategoryCheckExistsAsync(string categoryName, int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryOnCategoryId", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryOnCategoryIdResponse")]
        BusinessEntites.Admin.MasterCategoryDTO Admin_MasterCategoryOnCategoryId(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryOnCategoryId", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryOnCategoryIdResponse")]
        System.Threading.Tasks.Task<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryOnCategoryIdAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_BreakInformationCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_BreakInformationCheckExistsResponse")]
        System.Collections.Generic.List<BusinessEntites.BreakInformation> Admin_BreakInformationCheckExists(int breakInformationId, string breakType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_BreakInformationCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_BreakInformationCheckExistsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.BreakInformation>> Admin_BreakInformationCheckExistsAsync(int breakInformationId, string breakType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMasterCategoryChannel : ServiceClient.AdminMasterCategory.IMasterCategory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MasterCategoryClient : System.ServiceModel.ClientBase<ServiceClient.AdminMasterCategory.IMasterCategory>, ServiceClient.AdminMasterCategory.IMasterCategory {
        
        public MasterCategoryClient() {
        }
        
        public MasterCategoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MasterCategoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterCategoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterCategoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Admin_MasterCategoryUpdate(int categoryId, string categoryName, string viewTime) {
            base.Channel.Admin_MasterCategoryUpdate(categoryId, categoryName, viewTime);
        }
        
        public System.Threading.Tasks.Task Admin_MasterCategoryUpdateAsync(int categoryId, string categoryName, string viewTime) {
            return base.Channel.Admin_MasterCategoryUpdateAsync(categoryId, categoryName, viewTime);
        }
        
        public System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryGet() {
            return base.Channel.Admin_MasterCategoryGet();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO>> Admin_MasterCategoryGetAsync() {
            return base.Channel.Admin_MasterCategoryGetAsync();
        }
        
        public System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryCheckExists(string categoryName, int categoryId) {
            return base.Channel.Admin_MasterCategoryCheckExists(categoryName, categoryId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO>> Admin_MasterCategoryCheckExistsAsync(string categoryName, int categoryId) {
            return base.Channel.Admin_MasterCategoryCheckExistsAsync(categoryName, categoryId);
        }
        
        public BusinessEntites.Admin.MasterCategoryDTO Admin_MasterCategoryOnCategoryId(int categoryId) {
            return base.Channel.Admin_MasterCategoryOnCategoryId(categoryId);
        }
        
        public System.Threading.Tasks.Task<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryOnCategoryIdAsync(int categoryId) {
            return base.Channel.Admin_MasterCategoryOnCategoryIdAsync(categoryId);
        }
        
        public System.Collections.Generic.List<BusinessEntites.BreakInformation> Admin_BreakInformationCheckExists(int breakInformationId, string breakType) {
            return base.Channel.Admin_BreakInformationCheckExists(breakInformationId, breakType);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.BreakInformation>> Admin_BreakInformationCheckExistsAsync(int breakInformationId, string breakType) {
            return base.Channel.Admin_BreakInformationCheckExistsAsync(breakInformationId, breakType);
        }
    }
}
