//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanGoGoAdmin.GetListValues {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetListValues.IGetListValues")]
    public interface IGetListValues {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetListValues/Public_GetCityList", ReplyAction="http://tempuri.org/IGetListValues/Public_GetCityListResponse")]
        System.Collections.Generic.List<BusinessEntites.public_GetCityList> Public_GetCityList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetListValues/Public_GetCityList", ReplyAction="http://tempuri.org/IGetListValues/Public_GetCityListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.public_GetCityList>> Public_GetCityListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetListValues/Public_GetCategory", ReplyAction="http://tempuri.org/IGetListValues/Public_GetCategoryResponse")]
        System.Collections.Generic.List<BusinessEntites.Public_GetCategory> Public_GetCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetListValues/Public_GetCategory", ReplyAction="http://tempuri.org/IGetListValues/Public_GetCategoryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Public_GetCategory>> Public_GetCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetListValues/Public_FilterAttractions", ReplyAction="http://tempuri.org/IGetListValues/Public_FilterAttractionsResponse")]
        System.Collections.Generic.List<BusinessEntites.public_FilterAttractions> Public_FilterAttractions(string enterLocationName, System.Collections.Generic.List<BusinessEntites.userTable_Category> categoryList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetListValues/Public_FilterAttractions", ReplyAction="http://tempuri.org/IGetListValues/Public_FilterAttractionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.public_FilterAttractions>> Public_FilterAttractionsAsync(string enterLocationName, System.Collections.Generic.List<BusinessEntites.userTable_Category> categoryList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetListValues/Public_GetOrderOfAttractionVisit", ReplyAction="http://tempuri.org/IGetListValues/Public_GetOrderOfAttractionVisitResponse")]
        System.Collections.Generic.List<BusinessEntites.GetOrderOfAttractionVisit> Public_GetOrderOfAttractionVisit(int TravelModeId, int SourceAttractionID, int DestinationAttractionID, System.Collections.Generic.List<BusinessEntites.userTable_OnlyId> AttractionID, string StartDate, string StartTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetListValues/Public_GetOrderOfAttractionVisit", ReplyAction="http://tempuri.org/IGetListValues/Public_GetOrderOfAttractionVisitResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.GetOrderOfAttractionVisit>> Public_GetOrderOfAttractionVisitAsync(int TravelModeId, int SourceAttractionID, int DestinationAttractionID, System.Collections.Generic.List<BusinessEntites.userTable_OnlyId> AttractionID, string StartDate, string StartTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetListValues/GetAttractionOpenTime", ReplyAction="http://tempuri.org/IGetListValues/GetAttractionOpenTimeResponse")]
        System.Collections.Generic.List<BusinessEntites.GetAttractionOpenTime> GetAttractionOpenTime(int AttractionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetListValues/GetAttractionOpenTime", ReplyAction="http://tempuri.org/IGetListValues/GetAttractionOpenTimeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.GetAttractionOpenTime>> GetAttractionOpenTimeAsync(int AttractionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetListValuesChannel : PlanGoGoAdmin.GetListValues.IGetListValues, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetListValuesClient : System.ServiceModel.ClientBase<PlanGoGoAdmin.GetListValues.IGetListValues>, PlanGoGoAdmin.GetListValues.IGetListValues {
        
        public GetListValuesClient() {
        }
        
        public GetListValuesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetListValuesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetListValuesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetListValuesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BusinessEntites.public_GetCityList> Public_GetCityList() {
            return base.Channel.Public_GetCityList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.public_GetCityList>> Public_GetCityListAsync() {
            return base.Channel.Public_GetCityListAsync();
        }
        
        public System.Collections.Generic.List<BusinessEntites.Public_GetCategory> Public_GetCategory() {
            return base.Channel.Public_GetCategory();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Public_GetCategory>> Public_GetCategoryAsync() {
            return base.Channel.Public_GetCategoryAsync();
        }
        
        public System.Collections.Generic.List<BusinessEntites.public_FilterAttractions> Public_FilterAttractions(string enterLocationName, System.Collections.Generic.List<BusinessEntites.userTable_Category> categoryList) {
            return base.Channel.Public_FilterAttractions(enterLocationName, categoryList);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.public_FilterAttractions>> Public_FilterAttractionsAsync(string enterLocationName, System.Collections.Generic.List<BusinessEntites.userTable_Category> categoryList) {
            return base.Channel.Public_FilterAttractionsAsync(enterLocationName, categoryList);
        }
        
        public System.Collections.Generic.List<BusinessEntites.GetOrderOfAttractionVisit> Public_GetOrderOfAttractionVisit(int TravelModeId, int SourceAttractionID, int DestinationAttractionID, System.Collections.Generic.List<BusinessEntites.userTable_OnlyId> AttractionID, string StartDate, string StartTime) {
            return base.Channel.Public_GetOrderOfAttractionVisit(TravelModeId, SourceAttractionID, DestinationAttractionID, AttractionID, StartDate, StartTime);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.GetOrderOfAttractionVisit>> Public_GetOrderOfAttractionVisitAsync(int TravelModeId, int SourceAttractionID, int DestinationAttractionID, System.Collections.Generic.List<BusinessEntites.userTable_OnlyId> AttractionID, string StartDate, string StartTime) {
            return base.Channel.Public_GetOrderOfAttractionVisitAsync(TravelModeId, SourceAttractionID, DestinationAttractionID, AttractionID, StartDate, StartTime);
        }
        
        public System.Collections.Generic.List<BusinessEntites.GetAttractionOpenTime> GetAttractionOpenTime(int AttractionId) {
            return base.Channel.GetAttractionOpenTime(AttractionId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.GetAttractionOpenTime>> GetAttractionOpenTimeAsync(int AttractionId) {
            return base.Channel.GetAttractionOpenTimeAsync(AttractionId);
        }
    }
}
