CREATE TABLE [dbo].[Attractions] (
    [AttractionsId]                    INT            IDENTITY (1, 1) NOT NULL,
    [AttractionName]                   VARCHAR (500)  NULL,
    [AddressOne]                       VARCHAR (500)  NULL,
    [AddressTwo]                       VARCHAR (500)  NULL,
    [CityId]                           INT            NULL,
    [CategoryId]                       INT            NULL,
    [Longitude]                        VARCHAR (250)  NULL,
    [Latitude]                         VARCHAR (250)  NULL,
    [PlaceId]                          VARCHAR (250)  NULL,
    [RankId]                           INT            NULL,
    [CreatedDate]                      DATETIME       NULL,
    [CreatedBy]                        VARCHAR (250)  NULL,
    [ModifiedDate]                     DATETIME       NULL,
    [ModifiedBy]                       VARCHAR (250)  NULL,
    [GoogleSearchText]                 VARCHAR (500)  NULL,
    [GoogleWebSite]                    VARCHAR (500)  NULL,
    [GoogleICon]                       VARCHAR (500)  NULL,
    [GoogleInternational_phone_number] VARCHAR (500)  NULL,
    [Googleadr_address]                VARCHAR (2000) NULL,
    [GoogleName]                       VARCHAR (500)  NULL,
    [GoogleRating]                     VARCHAR (50)   NULL,
    [GoogleUser_ratings_total]         INT            NULL,
    [IsScannedNearBy] BIT NULL, 
    CONSTRAINT [PK_Attractions] PRIMARY KEY CLUSTERED ([AttractionsId] ASC)
);

