CREATE TABLE [dbo].[CityXGoogleType](
	[CityXGoogleTypeId] [int] IDENTITY(1,1) NOT NULL,
	[CityId] [int] NULL,
	[GoogleTypeID] [int] NULL,
 CONSTRAINT [PK_CityXGoogleType] PRIMARY KEY CLUSTERED 
(
	[CityXGoogleTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]