CREATE TYPE [dbo].[UserTable_UpdatedBreaks] AS TABLE(
	[RequestDate] [date] NULL,
	[IsUserInterestedDayBreak] [bit] NULL,
	[UpdateDayEndTime] [time](7) NULL,
	[UpdateDayStartTime] [time](7) NULL,
	[IsUserInterestedLunchBreak] [bit] NULL,
	[UpdatedLunchTime] [time](7) NULL,	
	[IsUserInterestedBreak] [bit] NULL,
	[UpdatedBreakTime] [time](7) NULL,	
	[IsUserInterestedDinnerBreak] [bit] NULL,
	[UpdatedDinnerTime] [time](7) NULL,	
	[IsBreakAdded] [bit] NULL,
	[BreakAttractionId] [int] NULL,
	[IsLunchAdded] [bit] NULL,
	[LunchAttractionId] [int] NULL,
	[IsDinnerAdded] [bit] NULL,
	[DinnerAttractionId] [int] NULL,
	[IsUserInterestedBreakFast] [bit] NULL,
	[UpdatedBreakFastTime] [time](7) NULL,	
	[IsBreakFastAdded] [bit] NULL,
	[BreakFastAttractionId] [int] NULL,
	[IsDayBreakAdded] [bit] NULL,
	[DayBreakAttractionId] [int] NULL,
	[NoOfCars] [int] NULL,
	[AverageMileage] [int] NULL,
	[NoOfRooms] [int] NULL,
	[BreakFastExpense] [decimal](18, 2) NULL,
	[LunchExpense] [decimal](18, 2) NULL,
	[BreakExpense] [decimal](18, 2) NULL,
	[DayBreakExpense] [decimal](18, 2) NULL,
	[DinnerExpense] [decimal](18, 2) NULL,
	[CarRentalExpense] [decimal](18, 2) NULL,
	[IsNoOfCarsUserUpdated] [bit] NULL,
	[IsAverageMileageUserUpdated] [bit] NULL,
	[IsCarRentalExpenseUserUpdated] [bit] NULL,
	[IsBreakFastExpenseUserUpdated] [bit] NULL,
	[IsLunchExpenseUserUpdated] [bit] NULL,
	[IsBreakExpenseUserUpdated] [bit] NULL,
	[IsDinnerExpenseUserUpdated] [bit] NULL,
	[IsDayBreakExpenseUserUpdated] [bit] NULL,
	[IsNoOfRoomsUserUpdated] [bit] NULL
)