//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanGoGoAdmin.MissingDistanceAttractionsRecords {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MissingDistanceAttractionsRecords.IMissingDistanceAttractionsRecords")]
    public interface IMissingDistanceAttractionsRecords {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissingDistanceAttractionsRecords/Admin_MissingDistanceAttrac" +
            "tionsRecordsGet", ReplyAction="http://tempuri.org/IMissingDistanceAttractionsRecords/Admin_MissingDistanceAttrac" +
            "tionsRecordsGetResponse")]
        System.Collections.Generic.List<BusinessEntites.Admin.MissingDistanceAttractionsRecordsDTO> Admin_MissingDistanceAttractionsRecordsGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissingDistanceAttractionsRecords/Admin_MissingDistanceAttrac" +
            "tionsRecordsGet", ReplyAction="http://tempuri.org/IMissingDistanceAttractionsRecords/Admin_MissingDistanceAttrac" +
            "tionsRecordsGetResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MissingDistanceAttractionsRecordsDTO>> Admin_MissingDistanceAttractionsRecordsGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissingDistanceAttractionsRecords/Admin_MissingDistanceAttrac" +
            "tionsRecordsXAttractionsGet", ReplyAction="http://tempuri.org/IMissingDistanceAttractionsRecords/Admin_MissingDistanceAttrac" +
            "tionsRecordsXAttractionsGetResponse")]
        System.Collections.Generic.List<BusinessEntites.Admin.MissingDistanceAttractionsRecordsDTO> Admin_MissingDistanceAttractionsRecordsXAttractionsGet(int MissingDistanceAttractionsRecordsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissingDistanceAttractionsRecords/Admin_MissingDistanceAttrac" +
            "tionsRecordsXAttractionsGet", ReplyAction="http://tempuri.org/IMissingDistanceAttractionsRecords/Admin_MissingDistanceAttrac" +
            "tionsRecordsXAttractionsGetResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MissingDistanceAttractionsRecordsDTO>> Admin_MissingDistanceAttractionsRecordsXAttractionsGetAsync(int MissingDistanceAttractionsRecordsID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMissingDistanceAttractionsRecordsChannel : PlanGoGoAdmin.MissingDistanceAttractionsRecords.IMissingDistanceAttractionsRecords, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MissingDistanceAttractionsRecordsClient : System.ServiceModel.ClientBase<PlanGoGoAdmin.MissingDistanceAttractionsRecords.IMissingDistanceAttractionsRecords>, PlanGoGoAdmin.MissingDistanceAttractionsRecords.IMissingDistanceAttractionsRecords {
        
        public MissingDistanceAttractionsRecordsClient() {
        }
        
        public MissingDistanceAttractionsRecordsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MissingDistanceAttractionsRecordsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MissingDistanceAttractionsRecordsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MissingDistanceAttractionsRecordsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BusinessEntites.Admin.MissingDistanceAttractionsRecordsDTO> Admin_MissingDistanceAttractionsRecordsGet() {
            return base.Channel.Admin_MissingDistanceAttractionsRecordsGet();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MissingDistanceAttractionsRecordsDTO>> Admin_MissingDistanceAttractionsRecordsGetAsync() {
            return base.Channel.Admin_MissingDistanceAttractionsRecordsGetAsync();
        }
        
        public System.Collections.Generic.List<BusinessEntites.Admin.MissingDistanceAttractionsRecordsDTO> Admin_MissingDistanceAttractionsRecordsXAttractionsGet(int MissingDistanceAttractionsRecordsID) {
            return base.Channel.Admin_MissingDistanceAttractionsRecordsXAttractionsGet(MissingDistanceAttractionsRecordsID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MissingDistanceAttractionsRecordsDTO>> Admin_MissingDistanceAttractionsRecordsXAttractionsGetAsync(int MissingDistanceAttractionsRecordsID) {
            return base.Channel.Admin_MissingDistanceAttractionsRecordsXAttractionsGetAsync(MissingDistanceAttractionsRecordsID);
        }
    }
}
