//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanGoGoAdmin.AttractionTravelTimeDistance {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AttractionTravelTimeDistance.IAttractionTravelTimeDistance")]
    public interface IAttractionTravelTimeDistance {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttractionTravelTimeDistance/Admin_AttractionTravelTimeDistan" +
            "ceGet", ReplyAction="http://tempuri.org/IAttractionTravelTimeDistance/Admin_AttractionTravelTimeDistan" +
            "ceGetResponse")]
        System.Collections.Generic.List<BusinessEntites.Admin.AttractionTravelTimeDistanceDTO> Admin_AttractionTravelTimeDistanceGet(int AttractionsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttractionTravelTimeDistance/Admin_AttractionTravelTimeDistan" +
            "ceGet", ReplyAction="http://tempuri.org/IAttractionTravelTimeDistance/Admin_AttractionTravelTimeDistan" +
            "ceGetResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.AttractionTravelTimeDistanceDTO>> Admin_AttractionTravelTimeDistanceGetAsync(int AttractionsId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAttractionTravelTimeDistanceChannel : PlanGoGoAdmin.AttractionTravelTimeDistance.IAttractionTravelTimeDistance, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttractionTravelTimeDistanceClient : System.ServiceModel.ClientBase<PlanGoGoAdmin.AttractionTravelTimeDistance.IAttractionTravelTimeDistance>, PlanGoGoAdmin.AttractionTravelTimeDistance.IAttractionTravelTimeDistance {
        
        public AttractionTravelTimeDistanceClient() {
        }
        
        public AttractionTravelTimeDistanceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AttractionTravelTimeDistanceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttractionTravelTimeDistanceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttractionTravelTimeDistanceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BusinessEntites.Admin.AttractionTravelTimeDistanceDTO> Admin_AttractionTravelTimeDistanceGet(int AttractionsId) {
            return base.Channel.Admin_AttractionTravelTimeDistanceGet(AttractionsId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.AttractionTravelTimeDistanceDTO>> Admin_AttractionTravelTimeDistanceGetAsync(int AttractionsId) {
            return base.Channel.Admin_AttractionTravelTimeDistanceGetAsync(AttractionsId);
        }
    }
}
