CREATE TYPE [dbo].[UserTable_GetOrderOfAttractionVisit] AS TABLE(
	SourceAttractionId INT,
	DestinationAttractionId INT,
	Distance Varchar(50),
	TravelTime Varchar(50),
	TravelModeId INT,
	SourceAttractionName Varchar(1000),
	DestinationAttractionName Varchar(1000),
	DateAndTime Varchar(50),
	ReachTime Varchar(50),
	TimeRequiredToView Varchar(50),
	EventEndTime Varchar(50),
	TravelType Varchar(1000),
	SourceIcon Varchar(1000),
	DestinationIcon Varchar(50),
	RecordCount INT,
	IsOrderUpdated BIT,
	UpdatedOrder INT,
	IsUpdatedViewTime BIT,
	UpdatedTime Varchar(50),
	IsPersonalRequest BIT,
	IsLunchDinnerBreakTime BIT,
	IsDistanceCalculationMissing BIT,
	SourceDirection Varchar(1000),
	DestinationDirection Varchar(1000),
	SourceRating Varchar(50),
	DestinationRating Varchar(50),
	SourceRatingTotal Varchar(50),
	DestinationRatingTotal Varchar(50),
	SourceSearchText Varchar(1000),
	DestinationSearchText Varchar(1000),
	SourceOpenTime Varchar(1000),
	SourceCloseTime Varchar(1000),
	DestinationOpenTime Varchar(1000),
	DestinationCloseTime Varchar(1000),
	SourcePhoto Varchar(1000),
	DestinationPhoto Varchar(1000),
	SourceLongitude Varchar(50),
	SourceLatitude Varchar(50),
	DestinationLongitude Varchar(50),
	DestinationLatitude Varchar(50),
	SourcePhotoUrl Varchar(1000) NULL,
	DestinationPhotoUrl Varchar(1000) NULL
)