CREATE TABLE [dbo].[MapFeatures](
	[MapFeaturesId] [int] NOT NULL,
	[FeatureName] [varchar](500) NULL,
 CONSTRAINT [PK_MapFeatures] PRIMARY KEY CLUSTERED 
(
	[MapFeaturesId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]