//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanGoGoAdmin.MasterWeek {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MasterWeek.IMasterWeek")]
    public interface IMasterWeek {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterWeek/Admin_MasterWeekGet", ReplyAction="http://tempuri.org/IMasterWeek/Admin_MasterWeekGetResponse")]
        System.Collections.Generic.List<BusinessEntites.Admin.MasterWeekDTO> Admin_MasterWeekGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterWeek/Admin_MasterWeekGet", ReplyAction="http://tempuri.org/IMasterWeek/Admin_MasterWeekGetResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MasterWeekDTO>> Admin_MasterWeekGetAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMasterWeekChannel : PlanGoGoAdmin.MasterWeek.IMasterWeek, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MasterWeekClient : System.ServiceModel.ClientBase<PlanGoGoAdmin.MasterWeek.IMasterWeek>, PlanGoGoAdmin.MasterWeek.IMasterWeek {
        
        public MasterWeekClient() {
        }
        
        public MasterWeekClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MasterWeekClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterWeekClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterWeekClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BusinessEntites.Admin.MasterWeekDTO> Admin_MasterWeekGet() {
            return base.Channel.Admin_MasterWeekGet();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MasterWeekDTO>> Admin_MasterWeekGetAsync() {
            return base.Channel.Admin_MasterWeekGetAsync();
        }
    }
}
