//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.MasterCategory {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MasterCategory.IMasterCategory")]
    public interface IMasterCategory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryUpdate", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryUpdateResponse")]
        void Admin_MasterCategoryUpdate(int categoryId, string categoryName, string viewTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryUpdate", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryUpdateResponse")]
        System.Threading.Tasks.Task Admin_MasterCategoryUpdateAsync(int categoryId, string categoryName, string viewTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryGet", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryGetResponse")]
        System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryGet", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryGetResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO>> Admin_MasterCategoryGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryCheckExistsResponse")]
        System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryCheckExists(string categoryName, int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryCheckExistsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO>> Admin_MasterCategoryCheckExistsAsync(string categoryName, int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryOnCategoryId", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryOnCategoryIdResponse")]
        BusinessEntites.Admin.MasterCategoryDTO Admin_MasterCategoryOnCategoryId(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryOnCategoryId", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryOnCategoryIdResponse")]
        System.Threading.Tasks.Task<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryOnCategoryIdAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_BreakInformationCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_BreakInformationCheckExistsResponse")]
        System.Collections.Generic.List<BusinessEntites.BreakInformation> Admin_BreakInformationCheckExists(int breakInformationId, string breakType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_BreakInformationCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_BreakInformationCheckExistsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.BreakInformation>> Admin_BreakInformationCheckExistsAsync(int breakInformationId, string breakType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterBreakInfoUpdate", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterBreakInfoUpdateResponse")]
        void Admin_MasterBreakInfoUpdate(int breakInformationId, string breakType, string startTime, string minimumTime, string display, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterBreakInfoUpdate", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterBreakInfoUpdateResponse")]
        System.Threading.Tasks.Task Admin_MasterBreakInfoUpdateAsync(int breakInformationId, string breakType, string startTime, string minimumTime, string display, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Scheduler_GetTravelMode", ReplyAction="http://tempuri.org/IMasterCategory/Scheduler_GetTravelModeResponse")]
        System.Collections.Generic.List<BusinessEntites.Common.MasterTravelModeDTO> Scheduler_GetTravelMode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Scheduler_GetTravelMode", ReplyAction="http://tempuri.org/IMasterCategory/Scheduler_GetTravelModeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Common.MasterTravelModeDTO>> Scheduler_GetTravelModeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_TravelModeCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_TravelModeCheckExistsResponse")]
        System.Collections.Generic.List<BusinessEntites.BreakInformation> Admin_TravelModeCheckExists(int travelModeId, string travelType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_TravelModeCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_TravelModeCheckExistsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.BreakInformation>> Admin_TravelModeCheckExistsAsync(int travelModeId, string travelType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_TravelModeUpdate", ReplyAction="http://tempuri.org/IMasterCategory/Admin_TravelModeUpdateResponse")]
        void Admin_TravelModeUpdate(int travelModeId, string travelType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_TravelModeUpdate", ReplyAction="http://tempuri.org/IMasterCategory/Admin_TravelModeUpdateResponse")]
        System.Threading.Tasks.Task Admin_TravelModeUpdateAsync(int travelModeId, string travelType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeGet", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeGetResponse")]
        System.Collections.Generic.List<BusinessEntites.DataBaseModels.MasterGoogleType> Admin_MasterGoogleTypeGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeGet", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeGetResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.DataBaseModels.MasterGoogleType>> Admin_MasterGoogleTypeGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeCheckExistsResponse")]
        System.Collections.Generic.List<BusinessEntites.DataBaseModels.MasterGoogleType> Admin_MasterGoogleTypeCheckExists(int googleTypeID, string typeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeCheckExists", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeCheckExistsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.DataBaseModels.MasterGoogleType>> Admin_MasterGoogleTypeCheckExistsAsync(int googleTypeID, string typeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeUpdate", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeUpdateResponse")]
        void Admin_MasterGoogleTypeUpdate(BusinessEntites.DataBaseModels.MasterGoogleType masterGoogleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeUpdate", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterGoogleTypeUpdateResponse")]
        System.Threading.Tasks.Task Admin_MasterGoogleTypeUpdateAsync(BusinessEntites.DataBaseModels.MasterGoogleType masterGoogleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryXMasterGoogleType", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryXMasterGoogleTypeResponse")]
        System.Collections.Generic.List<BusinessEntites.DataBaseModels.Admin_MasterCategoryXMasterGoogleType> Admin_MasterCategoryXMasterGoogleType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterCategory/Admin_MasterCategoryXMasterGoogleType", ReplyAction="http://tempuri.org/IMasterCategory/Admin_MasterCategoryXMasterGoogleTypeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.DataBaseModels.Admin_MasterCategoryXMasterGoogleType>> Admin_MasterCategoryXMasterGoogleTypeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMasterCategoryChannel : ServiceClient.MasterCategory.IMasterCategory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MasterCategoryClient : System.ServiceModel.ClientBase<ServiceClient.MasterCategory.IMasterCategory>, ServiceClient.MasterCategory.IMasterCategory {
        
        public MasterCategoryClient() {
        }
        
        public MasterCategoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MasterCategoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterCategoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterCategoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Admin_MasterCategoryUpdate(int categoryId, string categoryName, string viewTime) {
            base.Channel.Admin_MasterCategoryUpdate(categoryId, categoryName, viewTime);
        }
        
        public System.Threading.Tasks.Task Admin_MasterCategoryUpdateAsync(int categoryId, string categoryName, string viewTime) {
            return base.Channel.Admin_MasterCategoryUpdateAsync(categoryId, categoryName, viewTime);
        }
        
        public System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryGet() {
            return base.Channel.Admin_MasterCategoryGet();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO>> Admin_MasterCategoryGetAsync() {
            return base.Channel.Admin_MasterCategoryGetAsync();
        }
        
        public System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryCheckExists(string categoryName, int categoryId) {
            return base.Channel.Admin_MasterCategoryCheckExists(categoryName, categoryId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Admin.MasterCategoryDTO>> Admin_MasterCategoryCheckExistsAsync(string categoryName, int categoryId) {
            return base.Channel.Admin_MasterCategoryCheckExistsAsync(categoryName, categoryId);
        }
        
        public BusinessEntites.Admin.MasterCategoryDTO Admin_MasterCategoryOnCategoryId(int categoryId) {
            return base.Channel.Admin_MasterCategoryOnCategoryId(categoryId);
        }
        
        public System.Threading.Tasks.Task<BusinessEntites.Admin.MasterCategoryDTO> Admin_MasterCategoryOnCategoryIdAsync(int categoryId) {
            return base.Channel.Admin_MasterCategoryOnCategoryIdAsync(categoryId);
        }
        
        public System.Collections.Generic.List<BusinessEntites.BreakInformation> Admin_BreakInformationCheckExists(int breakInformationId, string breakType) {
            return base.Channel.Admin_BreakInformationCheckExists(breakInformationId, breakType);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.BreakInformation>> Admin_BreakInformationCheckExistsAsync(int breakInformationId, string breakType) {
            return base.Channel.Admin_BreakInformationCheckExistsAsync(breakInformationId, breakType);
        }
        
        public void Admin_MasterBreakInfoUpdate(int breakInformationId, string breakType, string startTime, string minimumTime, string display, string endTime) {
            base.Channel.Admin_MasterBreakInfoUpdate(breakInformationId, breakType, startTime, minimumTime, display, endTime);
        }
        
        public System.Threading.Tasks.Task Admin_MasterBreakInfoUpdateAsync(int breakInformationId, string breakType, string startTime, string minimumTime, string display, string endTime) {
            return base.Channel.Admin_MasterBreakInfoUpdateAsync(breakInformationId, breakType, startTime, minimumTime, display, endTime);
        }
        
        public System.Collections.Generic.List<BusinessEntites.Common.MasterTravelModeDTO> Scheduler_GetTravelMode() {
            return base.Channel.Scheduler_GetTravelMode();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.Common.MasterTravelModeDTO>> Scheduler_GetTravelModeAsync() {
            return base.Channel.Scheduler_GetTravelModeAsync();
        }
        
        public System.Collections.Generic.List<BusinessEntites.BreakInformation> Admin_TravelModeCheckExists(int travelModeId, string travelType) {
            return base.Channel.Admin_TravelModeCheckExists(travelModeId, travelType);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.BreakInformation>> Admin_TravelModeCheckExistsAsync(int travelModeId, string travelType) {
            return base.Channel.Admin_TravelModeCheckExistsAsync(travelModeId, travelType);
        }
        
        public void Admin_TravelModeUpdate(int travelModeId, string travelType) {
            base.Channel.Admin_TravelModeUpdate(travelModeId, travelType);
        }
        
        public System.Threading.Tasks.Task Admin_TravelModeUpdateAsync(int travelModeId, string travelType) {
            return base.Channel.Admin_TravelModeUpdateAsync(travelModeId, travelType);
        }
        
        public System.Collections.Generic.List<BusinessEntites.DataBaseModels.MasterGoogleType> Admin_MasterGoogleTypeGet() {
            return base.Channel.Admin_MasterGoogleTypeGet();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.DataBaseModels.MasterGoogleType>> Admin_MasterGoogleTypeGetAsync() {
            return base.Channel.Admin_MasterGoogleTypeGetAsync();
        }
        
        public System.Collections.Generic.List<BusinessEntites.DataBaseModels.MasterGoogleType> Admin_MasterGoogleTypeCheckExists(int googleTypeID, string typeName) {
            return base.Channel.Admin_MasterGoogleTypeCheckExists(googleTypeID, typeName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.DataBaseModels.MasterGoogleType>> Admin_MasterGoogleTypeCheckExistsAsync(int googleTypeID, string typeName) {
            return base.Channel.Admin_MasterGoogleTypeCheckExistsAsync(googleTypeID, typeName);
        }
        
        public void Admin_MasterGoogleTypeUpdate(BusinessEntites.DataBaseModels.MasterGoogleType masterGoogleType) {
            base.Channel.Admin_MasterGoogleTypeUpdate(masterGoogleType);
        }
        
        public System.Threading.Tasks.Task Admin_MasterGoogleTypeUpdateAsync(BusinessEntites.DataBaseModels.MasterGoogleType masterGoogleType) {
            return base.Channel.Admin_MasterGoogleTypeUpdateAsync(masterGoogleType);
        }
        
        public System.Collections.Generic.List<BusinessEntites.DataBaseModels.Admin_MasterCategoryXMasterGoogleType> Admin_MasterCategoryXMasterGoogleType() {
            return base.Channel.Admin_MasterCategoryXMasterGoogleType();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessEntites.DataBaseModels.Admin_MasterCategoryXMasterGoogleType>> Admin_MasterCategoryXMasterGoogleTypeAsync() {
            return base.Channel.Admin_MasterCategoryXMasterGoogleTypeAsync();
        }
    }
}
