//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanGoGoAdmin.AttractionsActiveStatus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AttractionsActiveStatus.IAttractionsActiveStatus")]
    public interface IAttractionsActiveStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttractionsActiveStatus/Admin_AttractionsActiveStatusGetOnAtt" +
            "ractionsActiveStatusId", ReplyAction="http://tempuri.org/IAttractionsActiveStatus/Admin_AttractionsActiveStatusGetOnAtt" +
            "ractionsActiveStatusIdResponse")]
        BusinessEntites.GetAttractionOpenTime Admin_AttractionsActiveStatusGetOnAttractionsActiveStatusId(int AttractionsActiveStatusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttractionsActiveStatus/Admin_AttractionsActiveStatusGetOnAtt" +
            "ractionsActiveStatusId", ReplyAction="http://tempuri.org/IAttractionsActiveStatus/Admin_AttractionsActiveStatusGetOnAtt" +
            "ractionsActiveStatusIdResponse")]
        System.Threading.Tasks.Task<BusinessEntites.GetAttractionOpenTime> Admin_AttractionsActiveStatusGetOnAttractionsActiveStatusIdAsync(int AttractionsActiveStatusId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAttractionsActiveStatusChannel : PlanGoGoAdmin.AttractionsActiveStatus.IAttractionsActiveStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttractionsActiveStatusClient : System.ServiceModel.ClientBase<PlanGoGoAdmin.AttractionsActiveStatus.IAttractionsActiveStatus>, PlanGoGoAdmin.AttractionsActiveStatus.IAttractionsActiveStatus {
        
        public AttractionsActiveStatusClient() {
        }
        
        public AttractionsActiveStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AttractionsActiveStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttractionsActiveStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttractionsActiveStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusinessEntites.GetAttractionOpenTime Admin_AttractionsActiveStatusGetOnAttractionsActiveStatusId(int AttractionsActiveStatusId) {
            return base.Channel.Admin_AttractionsActiveStatusGetOnAttractionsActiveStatusId(AttractionsActiveStatusId);
        }
        
        public System.Threading.Tasks.Task<BusinessEntites.GetAttractionOpenTime> Admin_AttractionsActiveStatusGetOnAttractionsActiveStatusIdAsync(int AttractionsActiveStatusId) {
            return base.Channel.Admin_AttractionsActiveStatusGetOnAttractionsActiveStatusIdAsync(AttractionsActiveStatusId);
        }
    }
}
